services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\ContextRibbon\Ribbon:
    public: true
  WapplerSystems\ContextRibbon\RibbonBackend:
    tags:
      - name: event.listener
        identifier: 'context-ribbon/backend/after-backend-page-render'
  WapplerSystems\ContextRibbon\RibbonFrontend:
    tags:
      - name: event.listener
        identifier: 'context-ribbon/frontend/modify-typo-script-config-event'
